name: Commit Stage

on:
  push:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/multi-arch-publish.yml
    strategy:
      fail-fast: false
      matrix:
        project: [
          {context: demo, image: buildpacks-demo-jvm},
          {context: demo-native, image: buildpacks-demo-native}
        ]
    with:
      context: ${{ matrix.project.context }}
      image: ${{ matrix.project.image }}
    secrets:  
      push-token: ${{ secrets.IMAGE_PUSH_TOKEN }}
